name: Deliveryman
version: '${version}'
main: com.platuro.delivery.Deliveryman
api-version: '1.20'
commands:
  openinventory:
    description: Open the courier inventory
    usage: /deliveryman openinventory
permissions:
  Deliveryman.openinventory:
    description: Allows opening the courier inventory
    default: true